/* ============================================================
   Strings — every sentence of the interface, in French and English
   ============================================================ */
(function () {
  "use strict";

  const add = window.__i18nAdd;
  const S = (table) => Object.keys(table).forEach((k) => add(k, table[k][0], table[k][1]));

  S({
    /* shell */
    "skip": ["Aller au contenu", "Skip to content"],
    "aria.info": ["Infos et heures du restaurant", "Restaurant info and hours"],
    "aria.search": ["Chercher dans le menu", "Search the menu"],
    "aria.lang": ["English version", "Version française"],
    "aria.mainNav": ["Navigation principale", "Main"],
    "aria.yourOrder": ["Votre commande", "Your order"],
    "aria.cartEmpty": ["Panier vide", "Cart, empty"],
    "aria.cartN.one": ["Panier, {n} article", "Cart, {n} item"],
    "aria.cartN.other": ["Panier, {n} articles", "Cart, {n} items"],
    "noscript": ["La commande en ligne demande JavaScript.", "Online ordering needs JavaScript."],
    "tab.menu": ["Menu", "Menu"],
    "tab.favorites": ["Favoris", "Favorites"],
    "tab.orders": ["Commandes", "Orders"],
    "tab.profile": ["Profil", "Profile"],
    "title.concept": ["concept non officiel", "unofficial concept"],
    "title.tracking": ["Suivi de commande", "Order tracking"],
    "nav.back": ["Retour", "Back"],
    "nav.backCart": ["Retour à la commande", "Back to your order"],
    "nav.close": ["Fermer", "Close"],

    /* menu */
    "status.open": ["Ouvert · jusqu’à {time}", "Open now · until {time}"],
    "status.soon": ["Ferme bientôt · {time}", "Closing soon · {time}"],
    "status.closed": ["Fermé", "Closed"],
    "status.opensToday": ["Fermé · ouvre à {time}", "Closed · opens {time}"],
    "status.opensTomorrow": ["Fermé · ouvre demain à {time}", "Closed · opens tomorrow {time}"],
    "status.opensDay": ["Fermé · ouvre {day} à {time}", "Closed · opens {day} {time}"],
    "concept.badge": ["Concept non officiel", "Unofficial concept"],
    "search.label": ["Chercher dans le menu", "Search the menu"],
    "search.placeholder": ["Poutine, avocat, Volcano…", "Poutine, avocado, Volcano…"],
    "search.cancel": ["Annuler", "Cancel"],
    "search.results": ["Résultats", "Results"],
    "search.none": ["Rien ne correspond à « {q} »", "Nothing matches “{q}”"],
    "search.try": ["Essayez un autre mot, comme « bol », « feta » ou « dessert ».", "Try another word, like “bowl”, “feta” or “dessert”."],
    "cats.label": ["Sections du menu", "Menu sections"],
    "count.items.one": ["{n} produit", "{n} item"],
    "count.items.other": ["{n} produits", "{n} items"],
    "price.from": ["Dès {price}", "From {price}"],
    "card.inCart": ["dans votre commande", "in your order"],
    "feature.eyebrow": ["Composez votre bol", "Build your bowl"],
    "feature.title": ["Le Rouge Bol, à votre façon", "The Rouge Bowl, your way"],
    "feature.desc": ["Saveur, bases, garnitures, sauces : votre bol se remplit sous vos yeux.", "Flavour, bases, toppings, sauces: watch your bowl fill up as you choose."],
    "fine.prices": ["Prix du menu de Montréal, à titre indicatif. TPS et TVQ ajoutées à la caisse.", "Montréal menu prices, for reference. GST and QST are added at checkout."],
    "fine.hours": ["Heures et restaurant", "Hours and restaurant"],
    "fav.label": ["Ajouter {name} aux favoris", "Favorite {name}"],

    /* the concept */
    "concept.short": ["Concept non officiel de {by}, sans lien avec Poulet Rouge. Aucune commande n’est envoyée.", "An unofficial concept by {by}, not affiliated with Poulet Rouge. No order is ever sent."],
    "concept.more": ["En savoir plus", "Learn more"],
    "concept.title": ["À propos de ce concept", "About this concept"],
    "concept.p1": ["Ce site est un concept non officiel de {by} : une idée de ce que pourrait être la commande en ligne chez Poulet Rouge. Il n’est ni affilié à Poulet Rouge, ni approuvé par la marque.",
      "This site is an unofficial concept by {by}: an idea of what ordering online from Poulet Rouge could feel like. It is not affiliated with or endorsed by Poulet Rouge."],
    "concept.p2": ["Aucune commande n’est transmise et rien n’est facturé. Vos choix restent sur cet appareil.", "No order is sent and nothing is charged. Your choices stay on this device."],
    "concept.p3": ["Les produits, les prix et les calories reprennent le menu public de Montréal (2026), à titre indicatif. Les photos viennent de banques d’images libres.",
      "Products, prices and calories follow the public Montréal menu (2026), for reference only. The photos come from free stock photo libraries."],
    "concept.link": ["Découvrir {by}", "More from {by}"],
    "credits.title": ["Crédits photo", "Photo credits"],
    "credits.note": ["Toutes les photos ont été recadrées et redimensionnées pour ce concept.", "Every photo was cropped and resized for this concept."],
    "credits.photo": ["photo", "photo"],
    "credits.by": ["par {by}", "by {by}"],
    "credits.on": ["sur {site}", "on {site}"],
    "credits.sep": [" : ", ": "],

    /* tabs */
    "fav.sub": ["Vos incontournables, à portée de main.", "Your go-tos, one tap away."],
    "fav.emptyTitle": ["Aucun favori pour l’instant", "No favorites yet"],
    "fav.emptyText": ["Touchez le cœur d’un produit pour le retrouver ici.", "Tap the heart on any item to keep it here."],
    "cta.browse": ["Voir le menu", "Browse the menu"],
    "cta.start": ["Commencer une commande", "Start an order"],
    "orders.sub": ["Suivez ce qui grille et recommandez en un geste.", "Follow what’s on the grill and reorder in one tap."],
    "orders.emptyTitle": ["Aucune commande", "No orders yet"],
    "orders.emptyText": ["Après votre première commande, vous pourrez la suivre ici, du gril jusqu’à vous.", "After your first order you can follow it here, from the grill to you."],
    "orders.live": ["En cours", "In progress"],
    "orders.past": ["Passées", "Past orders"],
    "orders.reorder": ["Recommander", "Reorder"],
    "orders.details": ["Détails", "Details"],
    "orders.track": ["Suivre", "Track"],
    "profile.title": ["Votre profil", "Your profile"],
    "profile.hi": ["Bonjour {name}", "Hi, {name}"],
    "profile.sub": ["Enregistré sur cet appareil pour commander plus vite.", "Saved on this device to make ordering quicker."],
    "profile.details": ["Vos coordonnées", "Your details"],
    "profile.saved": ["Enregistré", "Saved"],
    "profile.usual": ["Votre façon de commander", "How you usually order"],
    "profile.lang": ["Langue", "Language"],
    "profile.info": ["Heures et restaurant", "Hours and restaurant"],
    "profile.history": ["Historique des commandes", "Order history"],
    "reset.q": ["Effacer tout ce qui est enregistré sur cet appareil ?", "Clear everything saved on this device?"],
    "reset.text": ["Votre commande, vos favoris, votre historique, vos points et vos coordonnées seront supprimés.", "This removes your order, favorites, history, points and details."],
    "reset.yes": ["Effacer mes données", "Clear my data"],
    "reset.no": ["Garder", "Keep it"],
    "club.member": ["Membre", "Member"],
    "club.points": ["points", "points"],
    "club.rule": ["1 $ dépensé = {n} points.", "$1 spent = {n} points."],
    "club.welcome": ["Complétez votre profil pour recevoir {n} points de bienvenue.", "Complete your profile to get {n} welcome points."],
    "club.welcomed": ["Vos {n} points de bienvenue sont inclus.", "Your {n} welcome points are included."],
    "club.plus": ["+{n} points", "+{n} points"],

    /* fields */
    "field.name": ["Nom", "Name"],
    "field.namePh": ["Votre nom", "Your name"],
    "field.namePh2": ["Pour savoir à qui la remettre", "So we know who it’s for"],
    "field.phone": ["Téléphone", "Phone"],
    "field.phonePh": ["Pour les mises à jour de commande", "For order updates"],
    "field.phonePh2": ["Au cas où il faudrait vous joindre", "In case we need to reach you"],
    "field.address": ["Adresse de livraison", "Delivery address"],
    "field.addressPh": ["Rue, numéro, appartement", "Street, number, apartment"],
    "field.instructions": ["Instructions pour le livreur", "Instructions for the rider"],
    "field.instructionsPh": ["Interphone, étage, où la laisser", "Buzzer, floor, where to leave it"],
    "field.optional": ["Facultatif", "Optional"],
    "mode.label": ["Mode de commande", "Order type"],

    /* dish */
    "dish.minutes": ["{n} min", "{n} min"],
    "dish.kcal": ["{kcal} cal", "{kcal} Cal"],
    "dish.bowlAlt": ["{name} vu du dessus, avec vos choix", "{name} from above, with your choices"],
    "dish.photoAlt": ["{name}, vu du dessus", "{name} from above"],
    "dish.note": ["Instructions spéciales", "Special instructions"],
    "dish.notePh": ["Une précision pour le comptoir ?", "Anything the counter should know?"],
    "dish.notePhBowl": ["Sauce à part, peu de riz…", "Sauce on the side, light on rice…"],
    "dish.qty": ["Quantité", "Quantity"],
    "opt.choose1": ["Choisissez-en 1", "Choose 1"],
    "opt.upTo": ["Jusqu’à {n}", "Up to {n}"],
    "opt.range": ["De {min} à {max}", "{min} to {max}"],
    "opt.need.flavours": ["Choisissez au moins une saveur.", "Choose at least one flavour."],
    "opt.need.bases": ["Choisissez au moins une base.", "Choose at least one base."],
    "opt.need.toppings": ["Choisissez vos garnitures.", "Choose your toppings."],
    "opt.need.sauces": ["Choisissez une sauce.", "Choose a sauce."],
    "opt.need.flavor": ["Faites un choix.", "Make a choice."],
    "allergens.title": ["Allergènes :", "Allergens:"],
    "allergens.text": ["ce concept ne reproduit pas la liste officielle des allergènes de Poulet Rouge. En restaurant, demandez au comptoir avant de commander.",
      "this concept doesn’t reproduce Poulet Rouge’s official allergen list. In the restaurant, ask at the counter before you order."],
    "more.label": ["Plus d’options", "More options"],
    "more.copy": ["Copier le lien", "Copy link"],
    "more.allergens": ["Allergènes", "Allergens"],
    "total.price": ["Prix total", "Total price"],
    "cta.add": ["Ajouter", "Add to order"],
    "qty.less": ["Un de moins", "One less"],
    "qty.more": ["Un de plus", "One more"],
    "qty.remove": ["Retirer", "Remove"],
    "qty.of": ["Quantité de {name}", "Quantity of {name}"],

    /* cart */
    "cart.title": ["Ma commande", "My order"],
    "cart.clear": ["Vider", "Clear"],
    "cart.removeAll": ["Tout retirer", "Remove all"],
    "cart.keep": ["Garder", "Keep"],
    "cart.emptyTitle": ["Votre commande est vide", "Your order is empty"],
    "cart.emptyText": ["Composez un bol ou choisissez un extra : tout apparaîtra ici.", "Build a bowl or pick a side and it will show up here."],
    "cart.addMore": ["Ajouter autre chose", "Add something else"],
    "cart.how": ["Pour emporter ou en livraison ?", "Pickup or delivery?"],
    "cart.points": ["Cette commande vous rapporte {n} points {club}.", "This order earns you {n} {club} points."],
    "mode.pickupText": ["Au comptoir de {store}. Prête dans environ {n} min.", "At the {store} counter. Ready in about {n} min."],
    "mode.deliveryText": ["Livrée en environ {n} min.", "Delivered in about {n} min."],
    "mode.min": ["La livraison commence à {min} : ajoutez {gap}.", "Delivery starts at {min}: add {gap} more."],
    "mode.freeGap": ["Encore {gap} pour la livraison gratuite.", "Add {gap} more for free delivery."],
    "mode.freeNow": ["La livraison est offerte.", "Delivery is on us."],
    "sum.subtotal": ["Sous-total", "Subtotal"],
    "sum.delivery": ["Livraison", "Delivery"],
    "sum.free": ["Gratuite", "Free"],
    "sum.total": ["Total", "Total"],
    "cta.checkout": ["Finaliser", "Checkout"],

    /* checkout */
    "checkout.title": ["Finaliser la commande", "Checkout"],
    "checkout.change": ["Modifier", "Change"],
    "checkout.wherePickup": ["Au comptoir · {store}", "At the counter · {store}"],
    "checkout.whereDelivery": ["À votre porte", "To your door"],
    "checkout.demo": ["Concept : votre commande reste sur cet appareil. Aucun restaurant ne la reçoit et rien n’est facturé.", "Concept: your order stays on this device. No restaurant receives it and nothing is charged."],
    "when.pickup": ["Heure de ramassage", "Pickup time"],
    "when.delivery": ["Heure de livraison", "Delivery time"],
    "when.asap": ["Dès que possible", "As soon as possible"],
    "when.about": ["Environ {n} min", "About {n} min"],
    "when.closed": ["Fermé pour le moment", "We’re closed right now"],
    "when.schedule": ["Planifier", "Schedule"],
    "when.pick": ["Choisir une heure", "Pick a time"],
    "when.time": ["Heure", "Time"],
    "pay.title": ["Paiement", "Payment"],
    "pay.card": ["Carte", "Card"],
    "pay.cash": ["Comptant", "Cash"],
    "pay.counter": ["Au comptoir", "At the counter"],
    "pay.rider": ["Au livreur", "To the rider"],
    "pay.note": ["Vous payez en recevant votre commande. Aucune donnée de carte n’est demandée ici.", "You pay when you get your food. No card details are asked for here."],
    "cta.place": ["Commander", "Place order"],
    "err.address": ["Indiquez la rue, le numéro et l’appartement pour le livreur.", "Enter the street, number and apartment for the rider."],
    "err.name": ["Indiquez le nom pour cette commande.", "Enter the name for this order."],
    "err.phone": ["Indiquez un numéro de téléphone d’au moins 7 chiffres.", "Enter a phone number with at least 7 digits."],
    "err.slot": ["Choisissez une heure.", "Choose a time."],
    "err.closed": ["Le restaurant est fermé pour le moment. Choisissez une heure dans la liste.", "The restaurant is closed right now. Choose a time from the list."],
    "err.min": ["La livraison commence à {min}. Ajoutez {gap} ou choisissez pour emporter.", "Delivery starts at {min}. Add {gap} more or switch to pickup."],
    "err.emptyCart": ["Votre commande est vide.", "Your order is empty."],

    /* tracking */
    "order.title": ["Commande", "Order"],
    "order.number": ["Commande n° {n}", "Order #{n}"],
    "order.all": ["Toutes les commandes", "All orders"],
    "order.backMenu": ["Retour au menu", "Back to menu"],
    "order.yours": ["Votre commande", "Your order"],
    "order.details": ["Détails", "Details"],
    "order.type": ["Mode", "Order type"],
    "order.placed": ["Passée", "Placed"],
    "order.earned": ["{n} points {club} gagnés", "{n} {club} points earned"],
    "order.changeTitle": ["Un changement ?", "Need to change something?"],
    "order.changeText": ["Présentez-vous au comptoir en mentionnant la commande n° {n}.", "Ask at the counter and mention order #{n}."],
    "order.demo": ["Concept : le suivi avance tout seul pour vous montrer comment il fonctionne.", "Concept: the tracker moves along by itself so you can see it work."],
    "order.missingTitle": ["Commande introuvable", "We can’t find that order"],
    "order.missingText": ["Elle a peut-être été effacée de cet appareil.", "It may have been cleared from this device."],
    "order.seeAll": ["Voir mes commandes", "See your orders"],
    "stage.pickup.0": ["Commande reçue", "Order received"],
    "stage.pickup.1": ["Sur le gril", "On the grill"],
    "stage.pickup.2": ["Prête au comptoir", "Ready for pickup"],
    "stage.pickup.3": ["Récupérée", "Picked up"],
    "stage.delivery.0": ["Commande reçue", "Order received"],
    "stage.delivery.1": ["Sur le gril", "On the grill"],
    "stage.delivery.2": ["En route", "Out for delivery"],
    "stage.delivery.3": ["Livrée", "Delivered"],
    "track.received": ["Commande bien reçue", "We’ve got your order"],
    "track.scheduled": ["Prévue pour {time}", "Scheduled for {time}"],
    "track.cooking": ["Votre poulet est sur le gril", "Your chicken is on the grill"],
    "track.ready.pickup": ["Prête au comptoir", "Ready at the counter"],
    "track.ready.delivery": ["Votre livreur est en route", "Your rider is on the way"],
    "track.done.pickup": ["Récupérée. Bon appétit !", "Picked up. Enjoy!"],
    "track.done.delivery": ["Livrée. Bon appétit !", "Delivered. Enjoy!"],
    "track.thanks": ["Merci d’avoir commandé chez {name}.", "Thanks for ordering from {name}."],
    "track.readyAround": ["Prête vers {time}", "Ready around {time}"],
    "track.startAt": ["On lance le gril à {time}", "We’ll start grilling at {time}"],
    "track.leaving": ["Départ vers {time}", "Leaving around {time}"],
    "track.arriving": ["Arrivée vers {time}", "Arriving around {time}"],
    "track.askFor": ["Demandez la commande n° {n}", "Ask for order #{n}"],
    "track.placePickup": ["Au comptoir de {store}", "At the {store} counter"],
    "track.placeDelivery": ["Livraison au {address}", "To {address}"],
    "notify.cooking": ["La commande n° {n} est sur le gril", "Order #{n} is on the grill"],
    "notify.pickup": ["La commande n° {n} est prête au comptoir", "Order #{n} is ready at the counter"],
    "notify.delivery": ["La commande n° {n} est en route", "Order #{n} is on its way"],
    "notify.done": ["La commande n° {n} est terminée. Bon appétit !", "Order #{n} is complete. Enjoy!"],

    /* info drawer */
    "info.store": ["Votre restaurant", "Your restaurant"],
    "info.hours": ["Heures d’ouverture", "Opening hours"],
    "info.ways": ["Comment commander", "Ways to order"],
    "info.pickup": ["Prête en environ {n} minutes.", "Ready in about {n} minutes."],
    "info.delivery": ["Frais de {fee}, gratuite dès {free}. Commande minimum de {min}.", "{fee} fee, free from {free}. Minimum order {min}."],
    "days": ["Dimanche,Lundi,Mardi,Mercredi,Jeudi,Vendredi,Samedi", "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday"],
    "time.today": ["Aujourd’hui", "Today"],
    "time.tomorrow": ["Demain", "Tomorrow"],

    /* toasts */
    "toast.added": ["Ajouté : {qty} × {name}", "Added: {qty} × {name}"],
    "toast.viewCart": ["Voir la commande", "View order"],
    "toast.view": ["Voir", "View"],
    "toast.favOn": ["Ajouté aux favoris", "Saved to favorites"],
    "toast.favOff": ["Retiré des favoris", "Removed from favorites"],
    "toast.cleared": ["Commande vidée", "Order cleared"],
    "toast.placed": ["Commande n° {n} passée · +{pts} points", "Order #{n} placed · +{pts} points"],
    "toast.reordered.one": ["{n} article ajouté à votre commande", "{n} item added to your order"],
    "toast.reordered.other": ["{n} articles ajoutés à votre commande", "{n} items added to your order"],
    "toast.reorderNone": ["Ces produits ne sont plus au menu.", "Those items are no longer on the menu."],
    "toast.reset": ["Vos données ont été effacées de cet appareil", "Your data was cleared from this device"],
    "toast.welcome": ["+{n} points {club} : bienvenue !", "+{n} {club} points: welcome!"],
    "toast.copied": ["Copié", "Copied"],
    "toast.linkCopied": ["Lien copié", "Link copied"],
    "toast.copyFail": ["Impossible de copier. Sélectionnez le texte et copiez-le vous-même.", "Couldn’t copy. Select the text and copy it yourself."],
  });
})();
